movie_cast/config/routes.rb
Rails.application.routes.draw do
  root 'casts#index'
  get 'casts' => 'casts#index'

  post 'casts' => 'casts#create'
  get 'casts/new' => 'casts#new'

  get 'casts/:id/edit' => "casts#edit", as: "edit_cast"
  patch 'casts/:id' => "casts#update"

  get 'casts/:id' => 'casts#show', as: 'a_cast'

  delete 'casts/:id' => 'casts#destroy', as: 'delete_cast'

end

movie_cast/app/models/cast.rb
class Cast < ActiveRecord::Base
end

movie_cast/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

movie_cast/app/controllers/cast_controller.rb
class CastController < ApplicationController
  def index
    @movies = Cast.all
  end

  def show
    @movie = Cast.find(params[:id])
  end

  def create
    @movie = Cast.new(movie_params)
    if @movie.save
      redirect_to cast_url
    else
      render :new
    end
  end

  def new
    @movie = Cast.new
  end

  private
  def movie_params
    params.require(:movie).permit(:movie_title, :url)
  end

end

movie_cast/app/controllers/casts_controller.rb
class CastsController < ApplicationController
  def index
    @movie = Cast.all
  end

  def show
    @movie = Cast.find(params[:id])
  end

  def create
    @movie = Cast.new(movie_params)
    if @movie.save
      redirect_to casts_path
    else
      render :new
    end
  end

  def new
    @movie = Cast.new
  end

  def edit
    @movie = Cast.find(params[:id])
  end

  def updated
    @movie = Cast.find(params[:id])
    if @movie.update_attribute(movie_params)
      redirect_to 'casts/#{@movie.id}'
    else
      render :edit
    end
  end

  def destroy
    @movie = Cast.find(params[id])
    @movie.destroy
      redirect_to casts_url
  end

  private
  def movie_params
    params.require(:cast).permit(:movie_title, :url)
  end

end

movie_cast/app/helpers/application_helper.rb
module ApplicationHelper
end

movie_cast/app/helpers/cast_helper.rb
module CastHelper
end

movie_cast/app/views/cast/index.html.erb
<h1>Cast of movies</h1>

<ul>
<% @movies.each do |movie|%>
  <li><p><%= movie.movie_title%></p> </li>
  <img src="<%= movie.url %>">
<% end %>

</ul>

movie_cast/app/views/cast/new.html.erb
<h1>Add a movie and Cast!</h1>

<%= form_for @movie do |f|%>
  <p>
    <%= f.label :movie_title %><br>
    <%= f.text_field :movie_title %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

movie_cast/app/views/casts/edit.html.erb
<h1>Edit Movie Cast</h1>

<p>
  <%=link_to 'Back', @movie  %>
</p>

<%= form_for @movie do |f| %>
  <p>
     <%= f.label :movie_title %><br>
     <%= f.text_field :movie_title %>
   </p>
   <p>
     <%= f.label :url %><br>
     <%= f.text_field :url %>
   </p>
   <p>
     <%= f.submit %>
   </p>
  <% end %>

movie_cast/app/views/casts/index.html.erb
<h1>Cast of movies</h1>

<%= link_to "Add new Movie and Cast", "/casts/new" %>

<ul>
<% @movie.each do |movie|%>
  <li><p><%= movie.movie_title%></p> </li>
  <img src="<%= movie.url %>">
<% end %>

</ul>

movie_cast/app/views/casts/new.html.erb
<h1>Add a new movie and Cast!</h1>

<%= link_to "Back to Movie Casts", casts_url %>


<%= form_for @movie do |f|%>
  <p>
    <%= f.label :movie_title %><br>
    <%= f.text_field :movie_title %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

movie_cast/app/views/casts/show.html.erb
<%= link_to "Back to Movie Casts", casts_url %> | <%= link_to "Edit", edit_cast_path(@movie) %> | <%= link_to "Delete", delete_cast_path(@movie), method: :delete, data: {confirm: 'Are you sure you want to delete this picture?'} %>

<p><%=@movie.movie_title %></p>
<img src="<%= @movie.url %>" />

movie_cast/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieCast</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>